version: '3'

services:
  server:
    image: instantbox/instantbox:latest
    container_name: instantbox_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVERURL=
      - SWARM_MODE=0
    networks:
      - instantbox_net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  frontend:
    image: instantbox/instantbox-frontend:latest
    container_name: instantbox_frontend
    links:
      - server
    ports:
      - 8888:80
    networks:
      - instantbox_net
    deploy:
      mode: global

  cron:
    image: xordiv/docker-alpine-cron
    container_name: instantbox_cron
    links:
      - frontend
    environment:
      - CRON_STRINGS=* * * * * wget -qO /dev/null http://frontend/api/v2/superinspire/prune
    networks:
      - instantbox_net
    deploy:
      mode: replicated
      replicas: 1

networks:
  instantbox_net:
